# Generated by Django 3.0 on 2024-10-15 13:18

from django.db import migrations


def transfer_profiles_data(apps, schema_editor):
    # Récupérer l'ancien modèle Profile depuis oc_lettings_site
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    
    # Récupérer le nouveau modèle Profile depuis profiles
    NewProfile = apps.get_model('profiles', 'Profile')

    # Transférer les données de Profile
    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_profiles_data),
    ]
