# Generated by Django 3.0 on 2024-10-15 13:18

from django.db import migrations

def transfer_lettings_data(apps, schema_editor):
    # Récupérer les anciens modèles depuis oc_lettings_site
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    
    # Récupérer les nouveaux modèles depuis lettings
    NewAddress = apps.get_model('lettings', 'Address')
    NewLetting = apps.get_model('lettings', 'Letting')

    # Transférer les données de Address
    for old_address in OldAddress.objects.all():
        NewAddress.objects.create(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code
        )
    
    # Transférer les données de Letting
    for old_letting in OldLetting.objects.all():
        new_address = NewAddress.objects.get(
            number=old_letting.address.number,
            street=old_letting.address.street
        )
        NewLetting.objects.create(
            title=old_letting.title,
            address=new_address
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_lettings_data),
    ]
