# Generated by Django 3.0 on 2024-10-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_transfer_lettings_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
