name: Python application

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

permissions:
  contents: read


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest python-dotenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest python-dotenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest and display coverage report
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pytest --cov=./ --cov-report term --cov-fail-under=70

  containerize:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with commit hash tag
        env:
          COMMIT_HASH: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-python-app:${COMMIT_HASH} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-python-app:${COMMIT_HASH} ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:${COMMIT_HASH}
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest
